name: Test and Deploy to Vercel

# This workflow is triggered on push to the 'main' branch
on:
  push:
    branches:
      - main

jobs:
  # Job to run Cypress tests
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js (use Node.js version 18)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      # Step 3: Install project dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run Cypress tests
      - name: Run Cypress tests
        run: npx cypress run

  # Job to deploy to Vercel, runs only after Cypress tests pass
  deploy:
    needs: test  # This ensures the 'deploy' job only runs after 'test' job succeeds
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js (use Node.js version 18)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      # Step 3: Install project dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Deploy to Vercel
      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{secrets.VERCEL_TOKEN}}  # Use the Vercel token from GitHub Secrets
        run: npm run deploy
